# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogpostscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostscategory',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpostscategory',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
