# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180411_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='_slug',
            new_name='slug',
        ),
    ]
