# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_reports_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='member',
            name='priority',
            field=models.CharField(default='LOW', max_length=4),
        ),
    ]
