# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180412_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='priority',
            field=models.CharField(default='HIGH', max_length=4),
        ),
    ]
