# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('link', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
