# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-05 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180405_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_url', models.CharField(max_length=200)),
                ('user_check_url', models.CharField(max_length=200)),
            ],
        ),
    ]
