# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_check_priority'),
        ('api', '0002_auto_20180404_1723'),
    ]

    operations = [
    ]
