# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20180416_0815'),
        ('api', '0003_merge_20180412_1150'),
    ]

    operations = [
    ]
