# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-09 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_externalchecks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalchecks',
            old_name='user_check_url',
            new_name='check_url',
        ),
        migrations.RenameField(
            model_name='externalchecks',
            old_name='user_url',
            new_name='third_party_url',
        ),
    ]
