# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-10 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180409_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalchecks',
            name='name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
