# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-16 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20180416_0821'),
        ('api', '0004_check_is_alerted'),
    ]

    operations = [
    ]
