# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_externalchecks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalchecks',
            name='integration_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
