# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-11 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_externalchecks_integration_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalchecks',
            old_name='integration_timeout',
            new_name='ping_time_difference',
        ),
    ]
