# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-03 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180328_1603'),
        ('api', '0027_auto_20180328_1452'),
    ]

    operations = [
    ]
